version: '3'
services:
  database:
    image: postgres # use latest official postgres version
    ports:
      - "5433:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/docker_data/ # persist data even if container shuts down
  server:
    image: ee_card_server 
    links:
      - database 
    environment:
      DATABASE_URL: postgres://alevardai:dev_db@database:5432/ee_card 
    ports:
      - "8000:8000"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
