apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: DB_PORT
              value: '5432'
            - name: INTERNAL_DB_PORT
              value: '5433'
            - name: PORT
              value: '8000'
            - name: POSTGRES_DB
              value: ee_card
            - name: POSTGRES_PASSWORD
              value: ee_card_password
            - name: POSTGRES_URL
              value: postgres://user_card_user:ee_card_password@database:5432/ee_card
            - name: POSTGRES_USER
              value: user_card_user
          image: postgres
          name: database
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/docker_data
              name: database-data
      restartPolicy: Always
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-data
status: {}
