services:
  database:
    environment:
      DB_PORT: '5432'
      INTERNAL_DB_PORT: '5433'
      PORT: '8000'
      POSTGRES_DB: ee_card
      POSTGRES_PASSWORD: ee_card_password
      POSTGRES_URL: postgres://ee_card_user:ee_card_password@database:5432/ee_card
      POSTGRES_USER:ee_card_user 
    image: postgres
    ports:
    - published: 5433
      target: 5432
    volumes:
    - database-data:/var/lib/postgresql/docker_data:rw
  server:
    command: sh -c "chmod +x entrypoint-server.sh && ./entrypoint-server.sh"
    environment:
      DB_PORT: '5432'
      INTERNAL_DB_PORT: '5433'
      PORT: '8000'
      POSTGRES_DB: ee_card
      POSTGRES_PASSWORD: ee_card_password
      POSTGRES_URL: postgres://ee_card_user:ee_card_password@database:5432/ee_card
      POSTGRES_USER: ee_card_user 
    image: ee_card_server
    links:
    - database
    ports:
    - published: 8000
      target: 8000
version: '3.2'
volumes:
  database-data: {}

