apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yaml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yaml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - sh
            - -c
            - chmod +x entrypoint-server.sh && ./entrypoint-server.sh
          env:
            - name: DB_PORT
              value: '5432'
            - name: INTERNAL_DB_PORT
              value: '5433'
            - name: PORT
              value: '8000'
            - name: POSTGRES_DB
              value: ee_card
            - name: POSTGRES_PASSWORD
              value: ee_card_password
            - name: POSTGRES_URL
              value: postgres://ee_card_user:ee_card_password@database:5432/ee_card
            - name: POSTGRES_USER
              value: ee_card_user
          image: alevardai/ee_card_server:latest
          name: server
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
